spring.application.name=E-CommerceWebsite

server.port=8040
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerse
spring.datasource.username=root
spring.datasource.password=Kirti@2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=secretkey123
jwt.expiration=86400000
